// nuxtjs/pages/user/index/address.vue
<template>
    <el-card class="!border-none h-full" shadow="never">
        <div class="flex justify-between items-center mb-4">
            <h2 class="text-lg font-medium">地址管理</h2>
            <el-button type="primary" @click="handleAdd">新增地址</el-button>
        </div>
        
        <div v-if="addressList.length > 0" class="address-list">
            <div 
                v-for="item in addressList" 
                :key="item.id"
                class="address-item"
                :class="{ 'default': item.is_default === 1 }"
            >
                <div class="address-header">
                    <div class="flex items-center">
                        <span class="name mr-4">{{ item.name }}</span>
                        <span class="phone">{{ item.phone }}</span>
                        <el-tag v-if="item.is_default === 1" type="primary" size="small" class="ml-2">默认</el-tag>
                    </div>
                    <div class="address-actions">
                        <el-button type="text" @click="handleEdit(item)" size="small">编辑</el-button>
                        <el-button type="text" @click="handleDelete(item.id)" size="small" danger>
                            删除
                        </el-button>
                        <el-button 
                            v-if="item.is_default !== 1" 
                            type="text" 
                            @click="handleSetDefault(item.id)" 
                            size="small"
                        >
                            设为默认
                        </el-button>
                    </div>
                </div>
                <div class="address-content">
                    {{ item.province }} {{ item.city }} {{ item.district }} {{ item.address }}
                </div>
            </div>
        </div>
        
        <div v-else class="empty-address">
            <div class="empty-content text-center py-10">
                <el-icon class="empty-icon text-gray-300 text-5xl mb-4"><Location /></el-icon>
                <p class="text-gray-400">您还没有添加收货地址</p>
                <el-button type="primary" @click="handleAdd" class="mt-4">添加收货地址</el-button>
            </div>
        </div>
        
        <!-- 地址编辑弹窗 -->
        <el-dialog v-model="dialogVisible" :title="dialogTitle" width="600px" @close="handleClose">
            <el-form ref="addressFormRef" :model="addressForm" :rules="addressRules" label-width="80px">
                <el-form-item label="收货人" prop="name">
                    <el-input v-model="addressForm.name" placeholder="请输入收货人姓名" />
                </el-form-item>
                <el-form-item label="手机号" prop="phone">
                    <el-input v-model="addressForm.phone" placeholder="请输入收货人手机号" />
                </el-form-item>
                <el-form-item label="所在地区">
                    <el-cascader
                        v-model="addressForm.region"
                        :options="citys"
                        :props="regionProps"
                        placeholder="请选择省/市/区"
                        @change="handleRegionChange"
                    />
                </el-form-item>
                <el-form-item label="详细地址" prop="address">
                    <el-input
                        v-model="addressForm.address"
                        type="textarea"
                        placeholder="请输入详细地址信息"
                        :rows="3"
                    />
                </el-form-item>
                <el-form-item>
                    <el-switch 
                        v-model="addressForm.is_default" 
                        active-value="1" 
                        inactive-value="0"
                        active-text="设为默认地址"
                        inactive-text="设为默认地址"
                    />
                </el-form-item>
            </el-form>
            <template #footer>
                <span class="dialog-footer">
                    <el-button @click="handleClose">取消</el-button>
                    <el-button type="primary" @click="handleSubmit">确定</el-button>
                </span>
            </template>
        </el-dialog>
    </el-card>
</template>

<script setup lang="ts">
import { ref, onMounted, reactive } from 'vue'
import { Location } from '@element-plus/icons-vue'

import citys from '~/utils/citys'
import feedback from '~/utils/feedback'
import addressApi from '~/api/address'

// 地址列表
const addressList = ref<any[]>([])

// 弹窗状态
const dialogVisible = ref(false)
const dialogTitle = ref('新增地址')
const editingId = ref<number | null>(null)

// 表单引用
const addressFormRef = ref<any>()

// 表单数据
const addressForm = reactive({
    name: '',
    phone: '',
    region: [] as string[],
    province: '',
    city: '',
    district: '',
    address: '',
    is_default: '0'
})

// 表单验证规则
const addressRules = reactive<any>({
    name: [
        { required: true, message: '请输入收货人姓名', trigger: 'blur' }
    ],
    phone: [
        { required: true, message: '请输入收货人手机号', trigger: 'blur' },
        { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的手机号', trigger: 'blur' }
    ],
    address: [
        { required: true, message: '请输入详细地址', trigger: 'blur' }
    ]
})

const regionProps = {
    label: 'name',
    value: 'name',
    children: 'sub'
}

// 加载地址列表
const loadAddressList = async () => {
    try {
        const res = await addressApi.lists()
        if (res) {
            addressList.value = res
        }
    } catch (error) {
        feedback.msgError('获取地址列表失败')
    }
}

// 处理新增地址
const handleAdd = () => {
    dialogTitle.value = '新增地址'
    editingId.value = null
    resetForm()
    dialogVisible.value = true
}

// 处理编辑地址
const handleEdit = async (item: any) => {
    dialogTitle.value = '编辑地址'
    editingId.value = item.id
    
    // 填充表单数据
    addressForm.name = item.name
    addressForm.phone = item.phone
    addressForm.province = item.province
    addressForm.city = item.city
    addressForm.district = item.district
    addressForm.address = item.address
    addressForm.is_default = String(item.is_default)
    
    // 设置地区选择器的值
    addressForm.region = [item.province, item.city, item.district]
    
    dialogVisible.value = true
}

// 处理删除地址
const handleDelete = async (id: number) => {
    feedback.confirm('确定要删除此地址吗？')
        .then(async () => {
            try {
                const res = await addressApi.delete({ id })
                if (res >= 0) {
                    feedback.msgSuccess('删除成功')
                    await loadAddressList()
                } else {
                    feedback.msgError(res?.msg || '删除失败')
                }
            } catch (error) {
                feedback.msgError('删除失败')
            }
        })
        .catch(() => {})
}

// 处理设置默认地址
const handleSetDefault = async (id: number) => {
    try {
        const res = await addressApi.setDefault({ id })
        if (res >= 0) {
            feedback.msgSuccess('设置成功')
            await loadAddressList()
        } else {
            feedback.msgError('设置失败')
        }
    } catch (error) {
        feedback.msgError('设置失败')
    }
}

// 处理地区选择变化
const handleRegionChange = (values: any) => {
    if (values && Array.isArray(values) && values.length === 3) {
        addressForm.province = values[0]
        addressForm.city = values[1]
        addressForm.district = values[2]
    }
}

// 提交表单
const handleSubmit = async () => {
    if (!addressFormRef.value) return
    
    try {
        await addressFormRef.value.validate()
        
        const formData = {
            ...addressForm,
            is_default: Number(addressForm.is_default)
        }
        
        let res
        if (editingId.value) {
            res = await addressApi.edit({
                ...formData,
                id: editingId.value
            })
        } else {
            res = await addressApi.add(formData)
        }
        
        if (res >= 0) {
            feedback.msgSuccess(editingId.value ? '编辑成功' : '新增成功')
            handleClose()
            await loadAddressList()
        } else {
            feedback.msgError(res?.msg || (editingId.value ? '编辑失败' : '新增失败'))
        }
    } catch (error) {
        // 表单验证失败或API调用失败
    }
}

// 关闭弹窗
const handleClose = () => {
    dialogVisible.value = false
    resetForm()
}

// 重置表单
const resetForm = () => {
    if (addressFormRef.value) {
        addressFormRef.value.resetFields()
    }
    Object.assign(addressForm, {
        name: '',
        phone: '',
        region: [],
        province: '',
        city: '',
        district: '',
        address: '',
        is_default: '0'
    })
}

// 页面加载时获取地址列表
onMounted(async () => {
    await loadAddressList()
})
</script>

<style scoped lang="scss">
.address-list {
    .address-item {
        position: relative;
        padding: 20px;
        margin-bottom: 15px;
        border: 1px solid var(--el-border-color-light);
        border-radius: 8px;
        transition: all 0.3s;
        
        &:hover {
            box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.1);
        }
        
        &.default {
            border-color: var(--el-color-primary);
            background-color: rgba(64, 158, 255, 0.05);
            
            &::before {
                content: '';
                position: absolute;
                top: 0;
                left: 0;
                width: 4px;
                height: 100%;
                background-color: var(--el-color-primary);
                border-top-left-radius: 8px;
                border-bottom-left-radius: 8px;
            }
        }
        
        .address-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
            
            .name {
                font-weight: 500;
            }
            
            .phone {
                color: var(--el-text-color-secondary);
            }
        }
        
        .address-content {
            color: var(--el-text-color-regular);
            line-height: 1.6;
        }
    }
}

.empty-address {
    .empty-content {
        .empty-icon {
            opacity: 0.3;
        }
    }
}

:deep(.el-cascader) {
    width: 100%;
}

:deep(.el-dialog) {
    .el-form-item {
        margin-bottom: 20px;
    }
}
</style>

// miniprogram/src/pages/personal/address.tsx
import { useState, useCallback, useEffect } from "react";
import Taro from "@tarojs/taro";
import { View, Text } from "@tarojs/components";
import { Button, Popup, Form, Input, Address, TextArea } from "@nutui/nutui-react-taro";
import TopBar from "../../components/TopBar";
import addressApi from "../../api/address";
import { AddressItem, AddressAddIn, AddressEditIn, AddressIdParam } from "../../api/address/types";
import CityList from "../../utils/CityList";
import { Del, Plus, Edit } from "@nutui/icons-react-taro";
import './index.scss'; // 假设有样式文件

const AddressManage = () => {
  const [loading, setLoading] = useState<boolean>(false);
  const [addVisible, setAddVisible] = useState(false);
  const [editVisible, setEditVisible] = useState(false);
  const [addressList, setAddressList] = useState<AddressItem[]>([]);
  const [cityVisible, setCityVisible] = useState<boolean>(false);
  const [editingId, setEditingId] = useState<number | undefined | null>(null);
  const [selectedCity, setSelectedCity] = useState<string>("请选择位置");

  const [addForm] = Form.useForm();
  const [editForm] = Form.useForm();

  const initialAddValues = {
    name: "",
    phone: "",
    province: "",
    city: "",
    district: "",
    address: "",
    is_default: 1,
    full_address: "请选择位置"
  };

  const initialEditValues = { ...initialAddValues, id: 0 };

  useEffect(() => {
    refreshAddressList();
  }, []);

  const refreshAddressList = useCallback(() => {
    setLoading(true);
    addressApi.lists().then((res) => {
      setAddressList(res || []);
      setLoading(false);
    }).catch(() => {
      setLoading(false);
      Taro.showToast({ title: '加载失败', icon: 'none' });
    });
  }, []);

  const handleCityChange = useCallback((value: any, params: any) => {
    if (params && params.length >= 3) {
      const province = params[0].text;
      const city = params[1].text;
      const district = params[2].text;
      const full = params.map((it: any) => it.text).join(' ');
      setSelectedCity(full);
      if (addVisible) {
        addForm.setFieldsValue({ province, city, district, full_address: full });
      } else if (editVisible) {
        editForm.setFieldsValue({ province, city, district, full_address: full });
      }
      setCityVisible(false);
    }
  }, [addVisible, editVisible, addForm, editForm]);

  const handleAdd = useCallback((values: AddressAddIn) => {
    const submitData = {
      ...values,
      province: values.province || '',
      city: values.city || '',
      district: values.district || ''
    };
    addressApi.add(submitData).then((res) => {
      if (res) {
        Taro.showToast({ title: '添加成功', icon: 'success' });
        setAddVisible(false);
        addForm.resetFields();
        setSelectedCity("请选择位置");
        refreshAddressList();
      } else {
        Taro.showToast({ title: '添加失败', icon: 'none' });
      }
    }).catch(() => {
      Taro.showToast({ title: '添加失败', icon: 'none' });
    });
  }, [addForm, refreshAddressList]);

  const handleEdit = useCallback((values: AddressEditIn) => {
    if (!editingId) return;
    const submitData = {
      ...values,
      id: editingId,
      province: values.province || '',
      city: values.city || '',
      district: values.district || ''
    };
    addressApi.edit(submitData).then((res) => {
      if (res) {
        Taro.showToast({ title: '编辑成功', icon: 'success' });
        setEditVisible(false);
        editForm.resetFields();
        setEditingId(null);
        setSelectedCity("请选择位置");
        refreshAddressList();
      } else {
        Taro.showToast({ title: '编辑失败', icon: 'none' });
      }
    }).catch(() => {
      Taro.showToast({ title: '编辑失败', icon: 'none' });
    });
  }, [editingId, editForm, refreshAddressList]);

  const handleDelete = useCallback((id?: number) => {
    if (!id) return;
    Taro.showModal({
      title: '确认删除',
      content: '删除后不可恢复，确定要删除该地址吗？',
      success: (res) => {
        if (res.confirm) {
          addressApi.delete({ id }).then((result) => {
            if (result) {
              Taro.showToast({ title: '删除成功', icon: 'success' });
              refreshAddressList();
            } else {
              Taro.showToast({ title: '删除失败', icon: 'none' });
            }
          }).catch(() => {
            Taro.showToast({ title: '删除失败', icon: 'none' });
          });
        }
      }
    });
  }, [refreshAddressList]);

  const handleSetDefault = useCallback((id?: number ) => {
    if (!id) return;
    addressApi.setDefault({ id }).then((res) => {
      if (res) {
        Taro.showToast({ title: '设置默认成功', icon: 'success' });
        refreshAddressList();
      } else {
        Taro.showToast({ title: '设置失败', icon: 'none' });
      }
    }).catch(() => {
      Taro.showToast({ title: '设置失败', icon: 'none' });
    });
  }, [refreshAddressList]);

  const openEdit = useCallback((item: AddressItem) => {
    setEditingId(item.id);
    setSelectedCity(`${item.province} ${item.city} ${item.district}`);
    editForm.setFieldsValue({
      ...item,
      full_address: `${item.province} ${item.city} ${item.district}`,
      is_default: item.is_default || 0
    });
    setEditVisible(true);
    setAddVisible(false);
  }, [editForm]);

  const closeAdd = useCallback(() => {
    setAddVisible(false);
    addForm.resetFields();
    setSelectedCity("请选择位置");
  }, [addForm]);

  const closeEdit = useCallback(() => {
    setEditVisible(false);
    editForm.resetFields();
    setEditingId(null);
    setSelectedCity("请选择位置");
  }, [editForm]);

  return (
    <View className="min-h-screen bg-gray-50">
      <TopBar title="地址管理" showBack />

      <View className="flex flex-col gap-2 p-2">
        <View className="flex flex-row items-center justify-between">
          <Text className="text-md font-bold">我的地址</Text>
          <Button
            shape="square"
            fill="outline"
            type="primary"
            icon={<Plus size={10} color="#ff0f23" />}
            style={{ margin: 8 }}
            onClick={() => {
              setAddVisible(true);
            }}
          >
            添加地址
          </Button>
        </View>
        {loading ? <Text className="text-center">加载中...</Text> : null}
        <View className="flex flex-col gap-2">
          {addressList.map((item: AddressItem) => (
            <View
              key={item.id}
              className="flex flex-row justify-between items-start bg-white p-3 rounded-md shadow-sm"
            >
              <View className="flex-1">
                <View className="flex flex-row gap-2 mb-1">
                  <Text className="font-medium">{item.name}</Text>
                  <Text className="text-gray-700">{item.phone}</Text>
                  {item.is_default === 1 && <Text className="text-green-600 text-xs">默认</Text>}
                </View>
                <View className="text-gray-700 text-sm">
                  <Text>{`${item.province}${item.city}${item.district}${item.address}`}</Text>
                </View>
              </View>
              <View className="flex flex-row gap-1 ml-2">
                {!item.is_default && (
                  <Button
                    shape="square"
                    fill="outline"
                    type="primary"
                    size="small"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleSetDefault(item.id);
                    }}
                  >
                    设置默认
                  </Button>
                )}
                <Button
                  shape="square"
                  fill="outline"
                  type="info"
                  size="small"
                  icon={<Edit size={14} color="#1589f7" />}
                  onClick={(e) => {
                    e.stopPropagation();
                    openEdit(item);
                  }}
                />
                <Button
                  shape="square"
                  fill="none"
                  type="danger"
                  size="small"
                  icon={<Del size={18} color="#ff0f23" />}
                  onClick={(e) => {
                    e.stopPropagation();
                    handleDelete(item.id);
                  }}
                />
              </View>
            </View>
          ))}
        </View>
      </View>

      {/* 添加地址 Popup */}
      <Popup
        className="!z-[1002]"
        closeable
        title="添加地址"
        position="bottom"
        visible={addVisible}
        onClose={closeAdd}
      >
        <Form
          form={addForm}
          labelPosition="right"
          divider
          initialValues={initialAddValues}
          footer={
            <Button nativeType="submit" type="primary" block onClick={() => addForm.submit()}>
              保存
            </Button>
          }
          onFinish={handleAdd}
          onFinishFailed={(error) => {
            Taro.showToast({ title: JSON.stringify(error), icon: 'none' });
          }}
        >
          <Form.Item label="姓名" name="name" rules={[{ required: true, message: '请输入姓名' }]}>
            <Input className="!bg-gray-100" placeholder="请输入姓名" />
          </Form.Item>
          <Form.Item label="手机号" name="phone" rules={[{ required: true, message: '请输入手机号' }]}>
            <Input className="!bg-gray-100" placeholder="请输入手机号" type="tel" />
          </Form.Item>
          <Form.Item label="选择位置" name="full_address" rules={[{ required: true, message: '请选择位置' }]}>
            <Input
              className="!bg-gray-100"
              value={selectedCity}
              placeholder="请选择位置"
              onFocus={() => setCityVisible(true)}
              readOnly
            />
          </Form.Item>
          <Form.Item label="详细地址" name="address" rules={[{ required: true, message: '请输入详细地址' }]}>
            <TextArea className="!bg-gray-100" placeholder="请输入详细地址" />
          </Form.Item>
        </Form>
        <Address
          title="选择地址"
          options={CityList}
          visible={cityVisible && addVisible}
          onChange={handleCityChange}
          onClose={() => setCityVisible(false)}
        />
      </Popup>

      {/* 编辑地址 Popup */}
      <Popup
        className="!z-[1002]"
        closeable
        title="编辑地址"
        position="bottom"
        visible={editVisible}
        onClose={closeEdit}
      >
        <Form
          form={editForm}
          labelPosition="right"
          divider
          initialValues={initialEditValues}
          footer={
            <Button nativeType="submit" type="primary" block onClick={() => editForm.submit()}>
              保存
            </Button>
          }
          onFinish={handleEdit}
          onFinishFailed={(error) => {
            Taro.showToast({ title: JSON.stringify(error), icon: 'none' });
          }}
        >
          <Form.Item label="姓名" name="name" rules={[{ required: true, message: '请输入姓名' }]}>
            <Input className="!bg-gray-100" placeholder="请输入姓名" />
          </Form.Item>
          <Form.Item label="手机号" name="phone" rules={[{ required: true, message: '请输入手机号' }]}>
            <Input className="!bg-gray-100" placeholder="请输入手机号" type="tel" />
          </Form.Item>
          <Form.Item label="选择位置" name="full_address" rules={[{ required: true, message: '请选择位置' }]}>
            <Input
              className="!bg-gray-100"
              value={selectedCity}
              placeholder="请选择位置"
              onFocus={() => setCityVisible(true)}
              readOnly
            />
          </Form.Item>
          <Form.Item label="详细地址" name="address" rules={[{ required: true, message: '请输入详细地址' }]}>
            <TextArea className="!bg-gray-100" placeholder="请输入详细地址" />
          </Form.Item>
        </Form>
        <Address
          title="选择地址"
          options={CityList}
          visible={cityVisible && editVisible}
          onChange={handleCityChange}
          onClose={() => setCityVisible(false)}
        />
      </Popup>
    </View>
  );
};

export default AddressManage;
